# Generated by Django 4.2.4 on 2023-08-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("value", models.TextField()),
                ("timestamp", models.DateTimeField()),
            ],
        ),
    ]
